#!/usr/bin/env bash
# build.sh — generated by paper-covert
# Builds the submission PDF from latex/main.tex.
#
# Venue: RSE (Elsevier, fallback article class)
# Engine: pdflatex + bibtex (latexmk/xelatex not available in this environment)

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$HERE"

if command -v latexmk >/dev/null 2>&1; then
    latexmk -C main >/dev/null 2>&1 || true
    latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
else
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
    bibtex main || true
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
    pdflatex -interaction=nonstopmode -halt-on-error main.tex
fi

# Copy the final PDF up into the submission pdf/ folder.
mkdir -p "../pdf"
cp -f main.pdf "../pdf/MANUSCRIPT_SUBMISSION_READY.pdf"

# Summarize warnings. (grep -c always prints a count, even 0, on stdout regardless of its
# exit status -- do not also `|| echo 0`, that double-prints the line.)
{
  echo "# PDF build summary"
  echo
  echo "- Engine: pdflatex + bibtex (TeX Live 2018, no latexmk/xelatex installed)"
  echo "- Pages: $(grep -oE '\([0-9]+ pages' main.log | tail -1 | grep -oE '[0-9]+')"
  echo "- Overfull hbox: $(grep -c 'Overfull \\hbox' main.log)"
  echo "- Underfull hbox: $(grep -c 'Underfull \\hbox' main.log)"
  echo "- Undefined references: $(grep -ic 'undefined reference' main.log)"
  echo "- Undefined citations: $(grep -ic 'undefined citation' main.log)"
} > BUILD_NOTES.md
