#!/usr/bin/env python3
"""Independent holdout: the CURRENT shipped group3 classifier (Canola/Cereal/Legume, no
Grazing) scored on AgriWebb's 104 farmer-recorded crop paddock-years -- never trained on,
never touched during model development. The four existing `HOLDOUT_AGRIWEBB*.md` reports all
score the RETIRED 4-class (group4, with Grazing) model; this is the modern equivalent for the
architecture actually shipped, and the reason it matters: group4 called 39.4% of these same
paddocks "Grazing" (`HOLDOUT_AGRIWEBB.md`), which is exactly the failure mode that motivated
dropping Grazing for a presence gate in front of group3. This checks what group3 alone does
on the same independent paddocks.

Trains the identical temporal-transfer model already verified in `eval_predictions.py`
(Year<=2022, `keep_reviewed_SENSITIVE.csv`, seed 0) -- the same model whose numbers are in
`REVIEWED_MODEL.md` / the manuscript -- and scores it on AgriWebb's crop holdout, which was
never part of that training set at all (a genuinely external population, not held out from
it), so there is no temporal-leakage question the way there would be for NVT rows.

    python3 agriwebb_holdout_group3.py --seeds 0 1 2 3 4 \
        --out ../../output/HOLDOUT_AGRIWEBB_group3.md
"""
import argparse
import glob
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from train_species import build_features, GROUP  # noqa: E402
from eval_predictions import load, build_matrix  # noqa: E402

D = "/scratch/xe2/cb8590/paddock-species-data/derived"
AGRIWEBB_TS_GLOBS = [f"{D}/agriwebb/ts_idx/r*_ts_SENSITIVE.csv",
                     f"{D}/agriwebb/ts_idx/val_*_ts_SENSITIVE.csv"]
AGRIWEBB_VAL_SITES = f"{D}/agriwebb/val/agriwebb_val_sites_SENSITIVE.csv"


def build_agriwebb_matrix(train_columns):
    ts = load(AGRIWEBB_TS_GLOBS)
    value_cols = [c for c in ts.columns if c.endswith("_pad_median")]
    val = pd.read_csv(AGRIWEBB_VAL_SITES).drop_duplicates("TrialCode")
    n = ts.groupby("TrialCode").size()
    keep_obs = set(n[n >= 10].index)
    ts = ts[ts.TrialCode.isin(keep_obs)]
    Fx = build_features(ts, value_cols, False, val).reindex(columns=train_columns)
    y_true = val.set_index("TrialCode").reindex(Fx.index)["crop"]
    ok = y_true.notna()
    print(f"AgriWebb crop holdout: {len(Fx)} paddock-years with >=10 obs, "
          f"{ok.sum()} with a matched true label")
    return Fx.loc[ok].values, y_true.loc[ok].values, Fx.loc[ok].index.values


def run_seed(seed, X_train, y_train, X_test, y_test, classes):
    from sklearn.ensemble import HistGradientBoostingClassifier
    from sklearn.metrics import (f1_score, confusion_matrix, classification_report,
                                 balanced_accuracy_score)
    m = HistGradientBoostingClassifier(max_iter=400, learning_rate=0.06,
                                       class_weight="balanced", random_state=seed)
    m.fit(X_train, y_train)
    pred = m.predict(X_test)
    macro = f1_score(y_test, pred, average="macro")
    bal = balanced_accuracy_score(y_test, pred)
    cm = confusion_matrix(y_test, pred, labels=classes)
    rep = classification_report(y_test, pred, output_dict=True, zero_division=0)
    return {"seed": seed, "macro_f1": macro, "bal_acc": bal, "cm": cm, "report": rep,
            "pred": pred}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2, 3, 4])
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    F, X, y, meta, classes, scorable = build_matrix()
    tr = (meta.Year <= 2022).values  # identical temporal-transfer training set
    X_train, y_train = X[tr], y[tr]

    X_test, y_test, trialcodes = build_agriwebb_matrix(F.columns)
    print(f"train n={len(y_train)}, AgriWebb holdout n={len(y_test)}")
    print("true label counts:", pd.Series(y_test).value_counts().to_dict())

    all_results = [run_seed(s, X_train, y_train, X_test, y_test, classes) for s in args.seeds]
    for r in all_results:
        print(f"seed {r['seed']}: macro F1 {r['macro_f1']:.4f}")

    lines = ["# Independent holdout — AgriWebb crop events, CURRENT group3 model (no Grazing)",
              "",
              "Generated by `agriwebb_holdout_group3.py`. Aggregate only — no TrialCodes, "
              "no farm identifiers, matching this project's standing convention for "
              "committable classifier reports.",
              "",
              "Scores the identical temporal-transfer model already verified in "
              "`eval_predictions.py` / reported in `REVIEWED_MODEL.md` (train Year<=2022, "
              "`keep_reviewed_SENSITIVE.csv`) against AgriWebb's independent, "
              "farmer-recorded crop-paddock holdout — never used anywhere in training or "
              "model development. Supersedes `HOLDOUT_AGRIWEBB.md` / `_common86` / `_sam` / "
              "`_padcap`, which all scored the retired 4-class (group4, with Grazing) "
              "architecture; those reports are the reason Grazing was dropped in the first "
              "place (39.4% of these same paddocks called Grazing) and are not comparable "
              "to this one.",
              "",
              f"- scored: **{len(y_test)} paddock-years**, true label counts: " +
              ", ".join(f"{k} {v}" for k, v in pd.Series(y_test).value_counts().items()),
              "", "## Macro F1 by seed", "",
              "| seed | macro F1 | balanced accuracy |", "|---|---|---|"]
    for r in all_results:
        lines.append(f"| {r['seed']} | {r['macro_f1']:.4f} | {r['bal_acc']:.4f} |")
    f1s = [r["macro_f1"] for r in all_results]
    lines += ["", f"mean {np.mean(f1s):.4f}, sd {np.std(f1s):.4f}, "
                   f"range [{min(f1s):.4f}, {max(f1s):.4f}]", "",
              "**Caveat**: Legume has only 5 true examples in this holdout (vs. 109 in the "
              "NVT temporal/spatial test set) — its precision/recall/F1 below is not a "
              "reliable estimate on its own, just a data point. Canola (n=25) and Cereal "
              "(n=74) are the load-bearing classes in this comparison.", ""]

    r0 = all_results[0]
    lines += ["## Per-class precision/recall/F1 (seed " + str(r0["seed"]) + ")", "",
              "| class | precision | recall | F1 | n |", "|---|---|---|---|---|"]
    for c in classes:
        if c in r0["report"]:
            rr = r0["report"][c]
            lines.append(f"| {c} | {rr['precision']:.2f} | {rr['recall']:.2f} | "
                          f"{rr['f1-score']:.2f} | {int(rr['support'])} |")
    lines += ["", "## Confusion matrix (seed " + str(r0["seed"]) + ", row=truth, col=predicted)",
              "", "| |" + "|".join(c[:6] for c in classes) + "|",
              "|" + "---|" * (len(classes) + 1)]
    for i, c in enumerate(classes):
        lines.append(f"| **{c[:9]}** |" + "|".join(str(v) for v in r0["cm"][i]) + "|")

    lines += ["", "## Confusion matrices, all seeds", ""]
    for r in all_results:
        lines.append(f"**seed {r['seed']}**")
        lines.append("")
        lines.append("| |" + "|".join(c[:6] for c in classes) + "|")
        lines.append("|" + "---|" * (len(classes) + 1))
        for i, c in enumerate(classes):
            lines.append(f"| **{c[:9]}** |" + "|".join(str(v) for v in r["cm"][i]) + "|")
        lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}")

    # SENSITIVE per-site predictions (TrialCode + farm identifiers stay out of the committable
    # report above, matching this project's SENSITIVE-file convention).
    sens_out = f"{D}/agriwebb/val/agriwebb_group3_predictions_SENSITIVE.csv"
    pd.DataFrame({"TrialCode": trialcodes, "true": y_test,
                  "pred_seed0": r0["pred"]}).to_csv(sens_out, index=False)
    print(f"wrote {sens_out}")


if __name__ == "__main__":
    main()
