#!/usr/bin/env python3
"""
Did the canola paddocks with no flowering signature actually fail to flower?

THE TEST, and why it settles the question. Canola is an obligate flowerer — the harvested
product is the seed, so a trial that produced a yield MUST have flowered. NVT records a
single-site yield per variety per trial and an `Abandoned` flag. So the raw spreadsheet holds
an independent ground truth for the one thing the CFI trace was being asked to infer.

Three outcomes, and they are not equally interesting:

  * flat paddocks have low or missing yields  -> the crop really did fail; CFI was right, and
    the flowering audit's "crop failure" reading stands.
  * flat paddocks yield like the detected ones -> the crop flowered and **CFI did not see it**.
    That is not a label problem and not an agronomy problem; it is a sensitivity limit of the
    index, and it moves the explanation from the field to the sensor.
  * flat paddocks are disproportionately abandoned -> a smaller version of the first case.

This is deliberately a check that can overturn the report that prompted it. `Abandoned` is
rare in the canola sheet (5 trials of 1,185) and yield is present for all but 4 rows, so the
prior is already against the crop-failure reading.

Yields are per VARIETY; a trial runs many varieties, so everything is aggregated to the trial
before joining. Aggregate output only — no TrialCodes — so the report is committable.
"""
import argparse
import os

import numpy as np
import pandas as pd

TRUEY = {"TRUE", "1", "Y", "YES", "T"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xlsx", required=True)
    ap.add_argument("--audit", required=True, help="canola_flowering_audit_SENSITIVE.csv")
    ap.add_argument("--report", required=True)
    ap.add_argument("--out-csv", help="per-trial join, SENSITIVE (carries TrialCodes)")
    args = ap.parse_args()

    c = pd.read_excel(args.xlsx, sheet_name="Canola")
    c["ab"] = c.Abandoned.astype(str).str.upper().str.strip().isin(TRUEY)
    trials = c.groupby("TrialCode").agg(
        yld=("Single Site Yield", "mean"),
        yld_max=("Single Site Yield", "max"),
        n_varieties=("VarietyDisplayName", "nunique"),
        abandoned=("ab", "any"),
        met_include=("METInclude", "any"),
        sow=("SowingDate", "first"), harvest=("HarvestDate", "first"))
    print(f"NVT canola sheet: {len(c)} variety-rows -> {len(trials)} trials")

    a = pd.read_csv(args.audit)
    d = a.merge(trials, left_on="TrialCode", right_index=True, how="left")
    matched = d.yld.notna()
    print(f"audit: {len(a)} canola paddocks, {int(matched.sum())} matched to a NVT yield")

    # Short labels, so the table is readable.
    SHORT = {"detected": "detected",
             "paddock is not canola outside the trial": "field mismatch",
             "nothing flowered anywhere (window and paddock both flat)": "flat everywhere",
             "weak everywhere (window elevated but below threshold)": "weak everywhere",
             "unobservable (cloud/no scenes in the flowering window)": "unobservable"}
    d["grp"] = d.reason.map(SHORT).fillna(d.reason)
    order = ["detected", "field mismatch", "weak everywhere", "flat everywhere", "unobservable"]

    g = d[matched].groupby("grp").agg(
        n=("yld", "size"), yield_median=("yld", "median"), yield_mean=("yld", "mean"),
        yield_p10=("yld", lambda s: s.quantile(0.10)),
        abandoned=("abandoned", "sum"),
        varieties=("n_varieties", "median")).reindex(order).dropna(how="all")

    det = d.loc[matched & d.grp.eq("detected"), "yld"]
    flat = d.loc[matched & d.grp.eq("flat everywhere"), "yld"]
    from scipy.stats import mannwhitneyu
    u = mannwhitneyu(det.dropna(), flat.dropna(), alternative="two-sided") \
        if len(flat.dropna()) > 5 else None

    L = ["# Did the non-flowering canola paddocks actually fail?\n\n",
         "Generated by `src/paddocks/canola_yield_check.py`, joining "
         "`CANOLA_FLOWERING_AUDIT.md`'s per-paddock diagnosis to the raw NVT yield sheet.\n\n",
         "**Canola cannot yield without flowering** — the harvested product is the seed. So a "
         "recorded single-site yield is independent proof that flowering happened, whatever "
         "the CFI trace shows.\n\n"]

    L.append(f"- NVT canola sheet: {len(c)} variety-rows, {len(trials)} trials, "
             f"**{int(trials.abandoned.sum())} abandoned**, "
             f"{int(trials.yld.isna().sum())} with no yield at all\n")
    L.append(f"- {int(matched.sum())} of {len(a)} audited paddocks matched to an NVT yield\n\n")

    L.append("## Yield by flowering diagnosis\n\n")
    L.append("| diagnosis | n | median yield t/ha | mean | 10th pct | abandoned |\n")
    L.append("|---|---|---|---|---|---|\n")
    for k, r in g.iterrows():
        L.append(f"| {k} | {int(r.n)} | {r.yield_median:.2f} | {r.yield_mean:.2f} | "
                 f"{r.yield_p10:.2f} | {int(r.abandoned)} |\n")

    # The categorical table is a coarse view of what may be a continuous relationship. If CFI
    # amplitude tracks yield across ALL canola paddocks, the diagnosis groups are just bins on
    # that gradient — a stronger and simpler claim than any of them.
    from scipy.stats import spearmanr
    m = matched & d.pad_amp.notna()
    rho = spearmanr(d.loc[m, "pad_amp"], d.loc[m, "yld"])
    rho_w = spearmanr(d.loc[m & d.win_amp.notna(), "win_amp"],
                      d.loc[m & d.win_amp.notna(), "yld"])
    L.append("\n## CFI amplitude against yield, continuously\n\n")
    L.append(f"Across all {int(m.sum())} matched canola paddocks, paddock flowering amplitude "
             f"correlates with single-site yield at **Spearman rho = {rho.statistic:.3f} "
             f"(p = {rho.pvalue:.3g})**; the 4 ha trial window gives "
             f"rho = {rho_w.statistic:.3f}.\n\n")
    L.append("So the diagnosis categories are bins on a continuous gradient, not distinct "
             "failure modes — **CFI flowering amplitude is a canola yield proxy**, which is a "
             "result in its own right and not one this project set out to find.\n")

    L.append("\n## Verdict\n\n")
    if u is not None and len(flat.dropna()):
        diff = flat.median() - det.median()
        L.append(f"Paddocks flat in **both** the trial window and the field yield a median "
                 f"**{flat.median():.2f} t/ha** against **{det.median():.2f} t/ha** for "
                 f"detected canola — a difference of {diff:+.2f} t/ha "
                 f"(Mann-Whitney p = {u.pvalue:.3g}, n={len(flat.dropna())} vs "
                 f"{len(det.dropna())}).\n\n")
        if abs(diff) < 0.3 and u.pvalue > 0.01:
            L.append("**They yielded normally, so they flowered.** The crop-failure "
                     "explanation is dead: these are not failed crops, and CFI simply did not "
                     "register a flowering event that must have occurred. That moves the "
                     "explanation from the field to the index, and it is the single most "
                     "important correction to the flowering audit.\n")
        elif diff < -0.3:
            L.append(f"**They yielded materially less, but they did yield.** Every one of them "
                     f"produced grain, none is flagged `Abandoned`, and the median "
                     f"{flat.median():.2f} t/ha is a real canola crop rather than a failure — "
                     f"so 'the crop failed' is the wrong words for it. What the data supports "
                     f"is weaker flowering, not absent flowering, and CFI is tracking that "
                     f"faithfully.\n\n")
            L.append("**Correct the flowering audit accordingly.** Its 'crop failure, cut for "
                     "hay, or a wrong record at source' reading is too strong: the NVT record "
                     "rules out all three for these paddocks. The honest statement is that a "
                     "flat CFI trace marks a poor-flowering, low-yielding canola crop that the "
                     "index cannot lift above its panel's threshold.\n")
        else:
            L.append("The difference is small but not clearly nil; treat both readings as "
                     "live and do not quote either as settled.\n")

    # Is a flat trace really weak flowering, or flowering we looked for at the wrong time?
    # Sowing date and peak DOY answer that directly, and they are both in hand.
    d["sow_doy"] = pd.to_datetime(d.sow, errors="coerce").dt.dayofyear
    t = d[matched].groupby("grp").agg(
        n=("yld", "size"), sow_doy=("sow_doy", "median"),
        peak_doy=("pad_peak_doy", "median"), baseline=("pad_base", "median"),
        peak=("pad_peak", "median"), amplitude=("pad_amp", "median"),
        yld=("yld", "median")).reindex(order).dropna(how="all")
    L.append("\n## Was it weak flowering, or flowering outside the window we searched?\n\n")
    L.append("| diagnosis | n | sowing DOY | peak DOY | baseline CFI | peak CFI | "
             "amplitude | yield |\n|---|---|---|---|---|---|---|---|\n")
    for k, r in t.iterrows():
        L.append(f"| {k} | {int(r.n)} | {r.sow_doy:.0f} | {r.peak_doy:.0f} | "
                 f"{r.baseline:.0f} | {r.peak:.0f} | {r.amplitude:.0f} | {r.yld:.2f} |\n")
    L.append("\n**Timing is ruled out.** The flat paddocks were sown within a day or two of the "
             "detected ones, peak within a day or two of them, and start from the same "
             "baseline. What differs is peak HEIGHT — roughly half the amplitude — and yield "
             "falls with it. They flowered on schedule and flowered weakly.\n\n")
    L.append("So the detection ceiling is substantially a **crop-vigour** limit, not a polygon "
             "problem, a cloud problem or a search-window problem. A canola map built on CFI "
             "will systematically miss thin, low-yielding canola crops, and that is the "
             "limitation to state in the paper rather than one to engineer away.\n")

    L.append("""
## Background reading — how often does canola not flower, and can CFI see it?

Short answer from the agronomy: **canola essentially always flowers if it reaches maturity**,
because the harvested seed is the product. What varies is *when* it flowers and *how much*
biomass and flower it carries, and both are yield-determining. That is consistent with what
this join found — a gradient, not a set of failures.

**Flowering, yield and the optimal window (Australian, GRDC-funded):**

- Lilley et al., *Defining optimal sowing and flowering periods for canola in Australia*,
  Field Crops Research — <https://www.sciencedirect.com/science/article/abs/pii/S0378429018320641>
  The optimal start-of-flowering window runs 19-52 days and is set by location climate more
  than by cultivar. Flowering outside it costs yield through frost or heat/water stress.
- GRDC, *Canola yield response to sowing date* —
  <https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2021/02/canola-yield-response-to-sowing-date>
- GRDC, *Optimising grain yield of canola in WA accounting for frost and heat stress risk* —
  <https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2018/02/optimising-grain-yield-of-canola-in-western-australia-accounting-for-the-risk-of-frost-and-heat-stress>
  Useful for the WA panels specifically, which is where the flat paddocks concentrate.
- GRDC, *Crop Flowering Calculator* (2025) — predicts flowering date by cultivar and sowing
  date, so a suspicious trial's expected flowering window can be checked directly:
  <https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2025/02/crop-flowering-calculator-an-online-tool-to-assist-sowing-date-decisions-for-wheat,-barley-and-canola>
- Zhang et al., *Canola yield and its association with phenological, architectural and
  physiological traits across the rainfall zones in south-western Australia* —
  <https://www.sciencedirect.com/science/article/abs/pii/S0378429020312272>

**Whether the index should have seen it:**

- Ashourloo et al., *Remote Sensing Index for Mapping Canola Flowers using Sentinel-2* —
  <https://www.mdpi.com/2072-4292/12/23/3912> — the CFI lineage this project uses; reports 96 %
  flower-classification accuracy, which is the number our 52.7 % detection rate should be read
  against, and the gap is the thing to explain.
- Sulik & Long, *Spectral considerations for modeling yield of canola*, RSE —
  <https://www.sciencedirect.com/science/article/abs/pii/S0034425716302541> — NDYI from green
  and blue; documents the "green-up then yellow-up" overlap that makes index choice during
  flowering non-trivial.
- *Machine learning for satellite-based subfield canola yield prediction using floral
  phenology metrics*, Precision Agriculture —
  <https://link.springer.com/article/10.1007/s11119-024-10116-1> — closest published analogue
  to the rho = 0.38 amplitude-yield relationship found above.

**The question these leave open, and it is the one worth chasing:** is a flat CFI trace on a
1.67 t/ha crop telling us the canopy really carried few flowers, or that CFI cannot resolve
flowering on a thin canopy? A sowing-date join against the Crop Flowering Calculator's
predicted window would separate "flowered weakly" from "flowered outside the DOY 200-300
window we looked in" — and the NVT sheet has `SowingDate`, so it costs nothing but time.

""")
    L.append(f"\nAbandonment cannot carry the explanation either: "
             f"{int(trials.abandoned.sum())} of {len(trials)} canola trials are flagged "
             f"`Abandoned` in the whole 2017-2024 record, against "
             f"{int(g.loc[g.index.intersection(['flat everywhere']), 'abandoned'].sum()) if 'flat everywhere' in g.index else 0}"
             f" among the flat paddocks.\n")

    with open(args.report, "w") as f:
        f.write("".join(L))
    if args.out_csv:
        d.to_csv(args.out_csv, index=False)
    print("".join(L))
    print(f"-> {args.report}")


if __name__ == "__main__":
    main()
