#!/usr/bin/env python3
"""
Can a per-paddock score be used to filter the map down to something that matches ABS?

THE QUESTION, PRECISELY. `ABS_COMPARISON_100km.md` found the map calls 1.59x as much land crop
as ABS says was sown, and that the excess is labelled Cereal and Legume, which drags the canola
share 12 points low. The obvious remedy is not to delete anything but to SCORE every paddock and
let the reader choose a threshold: strict for an area-accurate map, permissive for "everything
with a crop-like season, including pasture that was sown and then grazed rather than harvested".

That only works if the score ORDERS paddocks by how likely they are to be the excess. This
script tests exactly that, and the test has a control, because the thing being asked of the
score is subtle: ANY filter that removes area moves the ratio toward 1.0, and — because the
excess is mostly Cereal — removing cereal-labelled area at random also moves the canola share
up. **A score is only useful if it beats removing the same amount of area at random.** Without
the control this experiment would confirm any score at all.

WHAT IS REPORTED. For each score and threshold: the area kept, the area ratio against ABS, and
the median absolute share error per crop, over the SA2-years the map censuses. Then the same
rows with a random score, averaged over `--n-random` draws, at matched retained area.

    python3 filter_sweep.py --attrs .../map100/attrs.parquet \
        --abs .../abs/abs_broadacre_area.csv --out ../../output/CONFIDENCE_FILTER.md
"""
import argparse

import numpy as np
import pandas as pd

CROPS = ["Canola", "Cereal", "Legume"]


def abs_shares(abs_csv):
    A = pd.read_csv(abs_csv, dtype={"region": str})
    A = A[A.level == "SA2"]
    W = (A.pivot_table(index=["region", "crop_year"], columns="group", values="area_ha",
                       aggfunc="sum").reindex(columns=CROPS).fillna(0.0))
    W["abs_crop_ha"] = W[CROPS].sum(axis=1)
    for c in CROPS:
        W[f"{c}_abs"] = W[c] / W.abs_crop_ha
    W.index.names = ["SA2_CODE21", "year"]
    return W


def score_rows(keep, W, key):
    """Per SA2-year: mapped shares, area ratio against ABS scaled to the covered fraction."""
    if not len(keep):
        return None
    mp = (keep.pivot_table(index=key, columns="pred", values="area_ha", aggfunc="sum")
              .reindex(columns=CROPS).fillna(0.0))
    tot = mp.sum(axis=1)
    sh = mp.div(tot, axis=0)
    cov = keep.groupby(key).cover_frac.first()
    j = sh.join(W[[f"{c}_abs" for c in CROPS] + ["abs_crop_ha"]], how="inner")
    if not len(j):
        return None
    j["mapped_ha"] = tot
    j["expected_ha"] = j.abs_crop_ha * cov
    j["area_ratio"] = j.mapped_ha / j.expected_ha
    return j


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--attrs", required=True)
    ap.add_argument("--abs", required=True)
    ap.add_argument("--min-cover", type=float, default=0.5)
    ap.add_argument("--min-abs-ha", type=float, default=5000.0)
    ap.add_argument("--n-random", type=int, default=20)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    T = pd.read_parquet(args.attrs) if args.attrs.endswith(".parquet") else pd.read_csv(args.attrs)
    W = abs_shares(args.abs)

    T = T[T.SA2_CODE21.notna()].copy()
    # SA2 codes are STRINGS on both sides — ABS publishes them zero-padded and the ASGS
    # shapefile stores them as text. Casting either side to int makes every key miss silently
    # and the whole comparison come back empty rather than wrong, which at least fails loudly.
    T["SA2_CODE21"] = T.SA2_CODE21.astype(str)
    key = ["SA2_CODE21", "year"]
    # The same restriction the ABS report uses: SA2s the box censuses, that are cropping regions.
    ok = T.cover_frac >= args.min_cover
    T = T[ok]
    big = W[W.abs_crop_ha >= args.min_abs_ha].index
    T = T[[k in set(big) for k in zip(T.SA2_CODE21, T.year)]]
    # abstain_reason, not pred, is authoritative for "cleanly classified" -- see
    # predict_tile.py's shape-gate comment (2026-09-07): a --shape-gate-skip-classes class can
    # carry a non-null pred alongside a non-empty abstain_reason, so pred.notna() alone would
    # wrongly count a gate-failed polygon as clean.
    cls = T[(T.abstain_reason.fillna("") == "") & T.pred.isin(CROPS)].copy()
    print(f"{len(T):,} polygon-years in censused cropping SA2s; {len(cls):,} classified")

    base = score_rows(cls, W, key)
    lines = ["# Can a per-paddock score filter the map to match ABS?", "",
             "Generated by `filter_sweep.py`. Every row below is the SAME map, filtered — nothing "
             "is re-run and nothing is thrown away on disk. The question is whether a score "
             "**orders** paddocks by how likely they are to be the 1.59x excess measured in "
             "`ABS_COMPARISON_100km.md`.", "",
             f"- {cls.SA2_CODE21.nunique()} SA2s x {cls.year.nunique()} years = "
             f"{len(base)} SA2-years, all at least {100 * args.min_cover:.0f} % covered",
             f"- unfiltered: **area ratio {base.area_ratio.median():.2f}**, canola share "
             f"{100 * base.Canola.median():.1f} % against ABS "
             f"{100 * base.Canola_abs.median():.1f} %", ""]

    scores = [("confidence", "max class probability — how sure the classifier is of the LABEL"),
              ("ndvi_amp", "NDVI amplitude — how strong the seasonal green-up is"),
              ("n_years", "years the polygon is found in — geometric stability, no spectra"),
              ("median_iou", "median IoU to the other years — geometric agreement"),
              ("n_obs", "clear Sentinel-2 observations behind the paddock series")]

    for col, blurb in scores:
        if col not in cls.columns or cls[col].isna().all():
            continue
        qs = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
        lines += ["", f"## `{col}`", "", blurb, "",
                  "| cut | threshold | area kept | area ratio | canola err | cereal err | legume err |",
                  "|---|---|---|---|---|---|---|"]
        for q in qs:
            t = cls[col].quantile(q)
            keep = cls[cls[col] >= t]
            j = score_rows(keep, W, key)
            if j is None:
                continue
            kept = keep.area_ha.sum() / cls.area_ha.sum()
            errs = [100 * float((j[c] - j[f"{c}_abs"]).abs().median()) for c in CROPS]
            lines.append(f"| drop bottom {100 * q:.0f} % | {t:.3g} | {100 * kept:.0f} % | "
                         f"**{j.area_ratio.median():.2f}** | {errs[0]:.1f} | {errs[1]:.1f} | "
                         f"{errs[2]:.1f} |")

    # THE VERDICT, COMPUTED. For each score, find the threshold that brings the area ratio
    # closest to 1.0 and report the share errors there — then say plainly whether it beat the
    # random control at the same retained area. Leaving this to the reader's eye over five
    # tables is how a score that does nothing gets adopted.
    verdict = []
    rng0 = np.random.default_rng(1)
    for col, _ in scores:
        if col not in cls.columns or cls[col].isna().all():
            continue
        best = None
        for q in np.arange(0.0, 0.85, 0.05):
            t = cls[col].quantile(q)
            keep = cls[cls[col] >= t]
            j = score_rows(keep, W, key)
            if j is None or not len(keep):
                continue
            r = j.area_ratio.median()
            cand = (abs(r - 1.0), q, t, keep.area_ha.sum() / cls.area_ha.sum(), r,
                    [100 * float((j[c] - j[f"{c}_abs"]).abs().median()) for c in CROPS])
            if best is None or cand[0] < best[0]:
                best = cand
        if best is None:
            continue
        _, q, t, kept, r, errs = best
        # The control at the SAME retained area, so the comparison is like for like.
        acc = []
        for _ in range(args.n_random):
            m = rng0.random(len(cls)) < kept
            j = score_rows(cls[m], W, key)
            if j is not None:
                acc.append([100 * float((j[c] - j[f"{c}_abs"]).abs().median()) for c in CROPS])
        rnd = np.mean(acc, axis=0)
        verdict.append((col, t, kept, r, errs, rnd))

    lines += ["", "## Verdict", "",
              "For each score: the threshold that lands the area ratio closest to 1.0, the share "
              "errors there, and — the part that matters — the same errors from removing the "
              "**same amount of area at random**. `beats random` is the canola improvement over "
              "that control.", "",
              "| score | threshold | area kept | ratio | canola err | vs random | cereal err | "
              "legume err |", "|---|---|---|---|---|---|---|---|"]
    for col, t, kept, r, errs, rnd in sorted(verdict, key=lambda v: v[4][0]):
        gain = rnd[0] - errs[0]
        mark = f"**-{gain:.1f} pts**" if gain > 1.0 else f"{-gain:+.1f} pts"
        lines.append(f"| `{col}` | {t:.3g} | {100 * kept:.0f} % | {r:.2f} | **{errs[0]:.1f}** | "
                     f"{mark} | {errs[1]:.1f} | {errs[2]:.1f} |")
    lines.append("")

    # THE CONTROL. Remove the same fraction of area at random, many times, and report the mean.
    # Any score that does not beat this is not finding the excess, it is only finding area.
    lines += ["", "## The control: removing the same area at random", "",
              "Polygons dropped uniformly at random to the same retained area, averaged over "
              f"{args.n_random} draws. **This is the bar.** Removing area at random also moves "
              "the ratio toward 1.0, and — because the excess is mostly Cereal — it moves the "
              "canola share up too. A score is only worth shipping if it beats this row.", "",
              "| area kept | area ratio | canola err | cereal err | legume err |",
              "|---|---|---|---|---|"]
    rng = np.random.default_rng(0)
    for frac in [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3]:
        acc = []
        for _ in range(args.n_random if frac < 1.0 else 1):
            m = rng.random(len(cls)) < frac
            j = score_rows(cls[m], W, key)
            if j is None:
                continue
            acc.append([j.area_ratio.median()] +
                       [100 * float((j[c] - j[f"{c}_abs"]).abs().median()) for c in CROPS])
        a = np.mean(acc, axis=0)
        lines.append(f"| {100 * frac:.0f} % | {a[0]:.2f} | {a[1]:.1f} | {a[2]:.1f} | {a[3]:.1f} |")

    # WHAT DOES THE MARGINAL LAND LOOK LIKE? If the excess were sown-then-grazed pasture it
    # should differ from the confidently-cropped paddocks somewhere measurable. This says where.
    lines += ["", "## What the marginal paddocks look like", "",
              "Classified paddocks split at the median of each score, so both halves hold the "
              "same number of paddocks. If the low half were the excess, it should differ in "
              "more than the score it was split on.", "",
              "| split | half | n | median ha | median ndvi_amp | median conf | median n_years | "
              "cereal share |", "|---|---|---|---|---|---|---|---|"]
    for col in ["confidence", "ndvi_amp", "n_years"]:
        if col not in cls.columns or cls[col].isna().all():
            continue
        med = cls[col].median()
        for lab, g in [("low", cls[cls[col] < med]), ("high", cls[cls[col] >= med])]:
            if not len(g):
                continue
            lines.append(
                f"| `{col}` | {lab} | {len(g):,} | {g.area_ha.median():.1f} | "
                f"{g.ndvi_amp.median():.2f} | {g.confidence.median():.3f} | "
                f"{g.n_years.median():.0f} | "
                f"{100 * g.loc[g.pred == 'Cereal', 'area_ha'].sum() / g.area_ha.sum():.0f} % |")
    lines.append("")

    open(args.out, "w").write("\n".join(lines) + "\n")
    print("\n".join(lines[:10]))
    print(f"\n-> {args.out}")


if __name__ == "__main__":
    main()
