#!/usr/bin/env python3
"""E9 (PAPER_PLAN.md §24 Open Issue #4), part 2: compare the national 2024 map against
NLUM v7 250m per-commodity probability surfaces (2021).

Unlike WorldCereal, NLUM has direct per-commodity layers for all three of our classes:
Canola -> oilseeds (W_OILSEEDS + S_OILSEEDS), Cereal -> cereals (W_CER + S_CER_EX_RICE),
Legume -> legumes (W_LEGUMES + S_LEGUMES). This is a probability-vs-class check, not a
class-vs-class confusion matrix: for each of our predicted classes, does the location sit
in an area NLUM rates as probable for the matching commodity? Also checks whether abstained
points sit preferentially in high-grazing-probability land (GRAZ_NOTIMBNP + GRAZ_NOTIMBSP),
the mechanism the project already suspected from prior NONCROP_CLASS.md work.

Uses the SAME sample (same seed) as worldcereal_compare.py so both halves of E9 describe the
identical point set.

    python3 nlum_compare.py --n-sample 250000 --out ../../output/NLUM_COMPARISON.md
"""
import argparse
import sys

import numpy as np
import pandas as pd
import rasterio
from pyproj import Transformer

CENTROIDS = "/scratch/xe2/cb8590/paddock-species-data/derived/national2024/fig_extract/national_2024_centroids.csv"
NLUM_DIR = "/g/data/xe2/cb8590/paddock-species-data/raw/NLUM_v7_250_AgProbabilitySurfaces_2020_21_geo_package_20241128"

LAYERS = {
    "oilseed": [f"{NLUM_DIR}/NLUM_v7_probSurf_2021_334_10_W_OILSEEDS.tif",
                f"{NLUM_DIR}/NLUM_v7_probSurf_2021_334_11_S_OILSEEDS.tif"],
    "cereal": [f"{NLUM_DIR}/NLUM_v7_probSurf_2021_331_5_W_CER.tif",
               f"{NLUM_DIR}/NLUM_v7_probSurf_2021_331_6_S_CER_EX_RICE.tif"],
    "legume": [f"{NLUM_DIR}/NLUM_v7_probSurf_2021_338_8_W_LEGUMES.tif",
               f"{NLUM_DIR}/NLUM_v7_probSurf_2021_338_9_S_LEGUMES.tif"],
    "grazing": [f"{NLUM_DIR}/NLUM_v7_probSurf_2021_210_1_GRAZ_NOTIMBNP.tif",
                f"{NLUM_DIR}/NLUM_v7_probSurf_2021_320_3_GRAZ_NOTIMBSP.tif"],
}
OUR_TO_NLUM = {"Canola": "oilseed", "Cereal": "cereal", "Legume": "legume"}


def sample_max(paths, lon, lat):
    """Max probability (%) across the seasonal variants of one commodity, per point."""
    vals = []
    for p in paths:
        src = rasterio.open(p)
        v = np.array(list(src.sample(list(zip(lon, lat)), indexes=1)), dtype=np.float64).ravel()
        v[v == src.nodata] = np.nan
        vals.append(v / 100.0)  # basis points (0-10000) -> percent (0-100)
        src.close()
    return np.nanmax(np.stack(vals), axis=0)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-sample", type=int, default=250_000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    df = pd.read_csv(CENTROIDS)
    n_total = len(df)
    df["cat"] = df["pred"].where(df["pred"].notna() & (df["pred"] != ""), "Abstained")

    n_sample = min(args.n_sample, n_total)
    sample = df.sample(n_sample, random_state=args.seed).sort_values(["cy", "cx"]).copy()

    tf = Transformer.from_crs("EPSG:3577", "EPSG:4326", always_xy=True)
    lon, lat = tf.transform(sample["cx"].to_numpy(), sample["cy"].to_numpy())

    print(f"sampling {n_sample:,} of {n_total:,} centroids against 4 NLUM commodity groups "
          f"(8 files)...", file=sys.stderr)
    for group, paths in LAYERS.items():
        sample[f"nlum_{group}"] = sample_max(paths, lon, lat)

    lines = []
    lines.append("# NLUM v7 (2021) per-commodity probability vs national 2024 crop-species map")
    lines.append("")
    lines.append("Generated by `nlum_compare.py`. Aggregate only — sampled paddock centroids "
                  "and probability-surface summaries, no site-level GRDC records.")
    lines.append("")
    lines.append("## Scope and caveats")
    lines.append("")
    lines.append("- NLUM gives a **probability surface per commodity**, not a hard "
                  "classification — this checks whether our predicted classes sit in areas "
                  "NLUM rates as probable for the matching commodity, not a confusion matrix.")
    lines.append("- Commodity groups combine seasonal variants by taking the max probability "
                  "(Oilseed = max(W_OILSEEDS, S_OILSEEDS), same pattern for Cereal/Legume) — "
                  "NLUM splits winter/summer cropping, our classes do not.")
    lines.append("- NLUM year is **2021** (v7 surfaces); our map is 2024 — same 3-year gap "
                  "already flagged for the WorldCereal half of E9.")
    lines.append(f"- Same {n_sample:,}-point sample (seed={args.seed}) as "
                  "`WORLDCEREAL_COMPARISON.md`, so both halves of E9 describe the identical "
                  "point set.")
    lines.append("")

    lines.append("## Median NLUM commodity probability (%), by our predicted class")
    lines.append("")
    lines.append("**Not comparable across columns** — NLUM's cereal-probability layer runs "
                  "much higher everywhere than its oilseed/legume layers (cereal cropping is "
                  "simply more widespread and less seasonally split in the underlying NLUM "
                  "model), so cereal will look elevated in every row regardless of agreement. "
                  "Read each column DOWN (does the probability for a commodity rise where our "
                  "map predicts that same commodity, relative to Abstained as the baseline "
                  "row), not across a row.")
    lines.append("")
    rows = []
    for our_cls in ["Canola", "Cereal", "Legume", "Abstained"]:
        sub = sample[sample["cat"] == our_cls]
        row = {"our class": f"{our_cls} (n={len(sub):,})"}
        for group in ["oilseed", "cereal", "legume", "grazing"]:
            row[group] = round(sub[f"nlum_{group}"].median(), 1)
        rows.append(row)
    med_df = pd.DataFrame(rows).set_index("our class")
    lines.append(med_df.to_markdown())
    lines.append("")

    lines.append("## Enrichment: median commodity probability relative to the Abstained baseline")
    lines.append("")
    lines.append("The scale-invariant version of the table above — each cell is "
                  "(median probability at our-class points) / (median probability at "
                  "Abstained points) for that SAME commodity layer, so cross-commodity scale "
                  "differences cancel out. >1 means our classified points sit in "
                  "higher-probability territory for that commodity than a typical abstained "
                  "point. **This still is not perfectly fair across commodities**: a "
                  "commodity with a low Abstained-baseline (oilseed, 1.1%) mechanically "
                  "produces larger ratios for a given absolute increase than one with a high "
                  "baseline near its 0-100% ceiling (cereal, 35.1%) — so an oilseed ratio "
                  "beating a cereal ratio in the same row is not by itself evidence of "
                  "stronger agreement. Compare within a column (down), not the size of the "
                  "diagonal entry against other cells in its own row.")
    lines.append("")
    baseline = med_df.loc[f"Abstained (n={(sample['cat']=='Abstained').sum():,})"]
    enrich_rows = []
    for our_cls in ["Canola", "Cereal", "Legume"]:
        r = med_df.loc[[i for i in med_df.index if i.startswith(our_cls)][0]]
        enrich_rows.append({"our class": our_cls, **{
            g: (round(r[g] / baseline[g], 2) if baseline[g] else float("nan"))
            for g in ["oilseed", "cereal", "legume"]}})
    lines.append(pd.DataFrame(enrich_rows).set_index("our class").to_markdown())
    lines.append("")

    lines.append("## Is our class the single best-matching NLUM commodity at that point?")
    lines.append("")
    lines.append("**Caveat**: this compares raw probability magnitudes ACROSS commodities, "
                  "which the enrichment table above shows is not scale-fair (NLUM's cereal "
                  "layer runs high everywhere) — a low match rate here mainly reflects that "
                  "imbalance, not necessarily classifier error. Included for completeness; "
                  "the enrichment table above is the fairer comparison.")
    lines.append("")
    lines.append("For each of our Canola/Cereal/Legume-classified points, which of NLUM's "
                  "three crop-commodity probabilities (oilseed/cereal/legume, ignoring "
                  "grazing) is highest at that location.")
    lines.append("")
    crop_probs = sample[["nlum_oilseed", "nlum_cereal", "nlum_legume"]]
    valid = crop_probs.notna().all(axis=1)
    n_dropped = (~valid).sum()
    if n_dropped:
        lines_note = (f"- {n_dropped:,} of {n_sample:,} points ({100*n_dropped/n_sample:.2f}%) "
                       "had no valid NLUM value in at least one commodity layer at that exact "
                       "pixel and are excluded from the argmax comparison below.")
    else:
        lines_note = None
    sample["nlum_top_commodity"] = pd.Series(index=sample.index, dtype=object)
    sample.loc[valid, "nlum_top_commodity"] = crop_probs.loc[valid].idxmax(axis=1).map(
        {"nlum_oilseed": "Canola", "nlum_cereal": "Cereal", "nlum_legume": "Legume"})
    if lines_note:
        lines.append(lines_note)
        lines.append("")
    for our_cls in ["Canola", "Cereal", "Legume"]:
        sub = sample[(sample["cat"] == our_cls) & valid]
        match_rate = 100 * (sub["nlum_top_commodity"] == our_cls).mean()
        lines.append(f"- **{our_cls}** (n={len(sub):,}): NLUM's top commodity agrees at "
                      f"**{match_rate:.1f}%** of points. Full breakdown: " +
                      ", ".join(f"{k} {v:.1f}%" for k, v in
                                (100 * sub['nlum_top_commodity'].value_counts(normalize=True)).items()))
    lines.append("")

    lines.append("## Abstained points: grazing probability check")
    lines.append("")
    abstained = sample[sample["cat"] == "Abstained"]
    classified = sample[sample["cat"] != "Abstained"]
    lines.append(f"- Median NLUM grazing probability at abstained points: "
                  f"**{abstained['nlum_grazing'].median():.1f}%** (n={len(abstained):,})")
    lines.append(f"- Median NLUM grazing probability at classified points: "
                  f"**{classified['nlum_grazing'].median():.1f}%** (n={len(classified):,})")
    lines.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
